version: '3'
services:
  application:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    image: andegna/vas-laravel:latest
    networks:
     - appnet
    volumes:
     - .:/var/www/html
    ports:
     - 8000:80
    working_dir: /var/www/html
  cache:
    image: redis:alpine
    networks:
     - appnet
    volumes:
     - cachedata:/data
  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
     - appnet
    volumes:
     - dbdata:/var/lib/mysql
  smsc:
    image: bulktrade/kannel:r5173
    networks:
      - appnet
    volumes:
      - "./docker/sms/kannel.conf:/etc/kannel/kannel.conf"
      - "./docker/sms/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: andegna/vas-node:latest
    networks:
     - appnet
    volumes:
     - .:/opt
    working_dir: /opt
    command: echo hi
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
