version: '3'
services:
  application.local:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    image: andegna/vas-laravel:latest
    networks:
     - appnet
    volumes:
     - .:/var/www/html
    ports:
     - 8000:80
    working_dir: /var/www/html
  cache.local:
    image: redis:alpine
    networks:
     - appnet
    volumes:
     - cachedata:/data
  database.local:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: vas
      MYSQL_USER: vas
      MYSQL_PASSWORD: sam
      MYSQL_ROOT_PASSWORD: sam
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
     - appnet
    volumes:
     - dbdata:/var/lib/mysql
  sms.local:
    image: bulktrade/kannel:r5173
    networks:
      - appnet
    volumes:
      - "./docker/sms/kannel.conf:/etc/kannel/kannel.conf"
      - "./docker/sms/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
  node.local:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: andegna/vas-node:latest
    networks:
     - appnet
    volumes:
     - .:/opt
    working_dir: /opt
    command: echo hi
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
