version: '3'
services:
  application:
    build:
      context: /ma~data/vas/docker/laravel
      dockerfile: Dockerfile
    image: andegna/vas-laravel:latest
    networks:
      - appnet
    volumes:
      - /ma~data/vas:/var/www/html
    ports:
      - 8000:80
    restart: always
    working_dir: /var/www/html
  cache:
    image: redis:alpine
    networks:
      - appnet
    restart: always
    volumes:
      - cachedata:/data
  database:
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: vas
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - appnet
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
  smsc:
    image: bulktrade/kannel:r5173
    networks:
      - appnet
    restart: always
    volumes:
      - "/ma~data/vas/docker/sms/kannel.conf:/etc/kannel/kannel.conf"
      - "/ma~data/vas/docker/sms/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
